apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "senha132132"  # Defina uma senha adequada aqui
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: bancodesafio
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgresdb