apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: teste
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer  # Para acesso externo; use ClusterIP para acesso interno
  ports:
  - port: 9000
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
